#!/usr/bin/env python

from PyQt5 import QtGui, QtQml
import os
import sys
import rospkg

import pynow


def main():
    app = QtGui.QGuiApplication([])
    engine = QtQml.QQmlApplicationEngine()

    context = engine.rootContext()
    now_model = pynow.NowModel()
    context.setContextProperty('now_model', now_model)

    qml_filename = os.path.join(rospkg.RosPack().get_path('now'), 'resources', 'now.qml')
    engine.load(qml_filename)

    qml_root = engine.rootObjects()[0]
    qml_root.updateModel.connect(now_model.update)

    app.exec_()
    del engine
    sys.exit()

if __name__ == "__main__":
    main()